import type { Match, TeamStanding, Scorer, LeagueGroup, Challenge, Player } from './types';

export const matches: Match[] = [
  { id: 1, league: 'دوري أبطال أوروبا', home: 'ريال مدريد', away: 'برشلونة', homeShort: 'ر م', awayShort: 'ب', time: '23:00', points: 5, featured: true, status: 'upcoming' },
  { id: 2, league: 'الدوري الإنجليزي', home: 'مانشستر يونايتد', away: 'نيوكاسل', homeShort: 'م ي', awayShort: 'ن', time: '22:00', points: 3, status: 'upcoming' },
  { id: 3, league: 'الدوري الإسباني', home: 'أتلتيكو مدريد', away: 'إشبيلية', homeShort: 'أ', awayShort: 'إ', time: '22:00', points: 3, status: 'upcoming' },
  { id: 4, league: 'دوري روشن السعودي', home: 'الهلال', away: 'الاتحاد', homeShort: 'هـ', awayShort: 'ا', time: '20:00', points: 5, featured: true, status: 'upcoming' },
  { id: 5, league: 'الدوري الإنجليزي', home: 'ليفربول', away: 'تشيلسي', homeShort: 'ل', awayShort: 'ت', time: '18:30', points: 3, status: 'finished', result: '2-1', homeGoals: 2, awayGoals: 1, correctPct: 34, wrongPct: 66 },
  { id: 6, league: 'الدوري الإسباني', home: 'فالنسيا', away: 'ريال سوسيداد', homeShort: 'ف', awayShort: 'ر س', time: '16:00', points: 3, status: 'finished', result: '0-0', homeGoals: 0, awayGoals: 0, correctPct: 28, wrongPct: 72 },
  { id: 7, league: 'دوري أبطال أوروبا', home: 'بايرن ميونخ', away: 'باريس سان جيرمان', homeShort: 'ب م', awayShort: 'ب س', time: '21:00', points: 5, featured: true, status: 'live' },
];

export const leagueGroups: LeagueGroup[] = [
  { title: 'أقوى البطولات المحلية', items: ['الدوري الإنجليزي', 'الدوري الإسباني', 'الدوري الإيطالي', 'الدوري الألماني', 'الدوري الفرنسي', 'دوري روشن السعودي'] },
  { title: 'بطولات الاتحادات القارية للاندية', items: ['دوري أبطال أوروبا', 'دوري أبطال إفريقيا', 'دوري أبطال آسيا', 'الدوري الأوروبي'] },
  { title: 'بطولات الاتحادات القارية للمنتخبات', items: ['كأس الأمم الأوروبية', 'كوبا أمريكا', 'كأس أمم إفريقيا', 'كأس أمم آسيا'] },
  { title: 'البطولات العالمية (الفيفا)', items: ['كأس العالم للمنتخبات', 'كأس العالم للأندية'] },
];

export const standings: Record<string, TeamStanding[]> = {
  'الدوري الإنجليزي': [
    { pos: 1, team: 'مانشستر سيتي', played: 24, won: 18, drawn: 4, lost: 2, gd: 38, pts: 58 },
    { pos: 2, team: 'ليفربول', played: 24, won: 17, drawn: 5, lost: 2, gd: 31, pts: 56 },
    { pos: 3, team: 'أرسنال', played: 24, won: 16, drawn: 4, lost: 4, gd: 25, pts: 52 },
    { pos: 4, team: 'أستون فيلا', played: 24, won: 14, drawn: 5, lost: 5, gd: 18, pts: 47 },
    { pos: 5, team: 'توتنهام', played: 24, won: 13, drawn: 6, lost: 5, gd: 12, pts: 45 },
    { pos: 6, team: 'مانشستر يونايتد', played: 24, won: 12, drawn: 5, lost: 7, gd: 5, pts: 41 },
    { pos: 7, team: 'نيوكاسل', played: 24, won: 11, drawn: 7, lost: 6, gd: 8, pts: 40 },
    { pos: 8, team: 'تشيلسي', played: 24, won: 10, drawn: 8, lost: 6, gd: 3, pts: 38 },
  ],
  'الدوري الإسباني': [
    { pos: 1, team: 'ريال مدريد', played: 24, won: 19, drawn: 3, lost: 2, gd: 42, pts: 60 },
    { pos: 2, team: 'برشلونة', played: 24, won: 16, drawn: 5, lost: 3, gd: 28, pts: 53 },
    { pos: 3, team: 'أتلتيكو مدريد', played: 24, won: 15, drawn: 4, lost: 5, gd: 20, pts: 49 },
    { pos: 4, team: 'أتلتيك بلباو', played: 24, won: 13, drawn: 6, lost: 5, gd: 15, pts: 45 },
    { pos: 5, team: 'ريال سوسيداد', played: 24, won: 12, drawn: 5, lost: 7, gd: 8, pts: 41 },
    { pos: 6, team: 'إشبيلية', played: 24, won: 10, drawn: 7, lost: 7, gd: 2, pts: 37 },
  ],
  'دوري أبطال أوروبا': [
    { pos: 1, team: 'ريال مدريد', played: 6, won: 6, drawn: 0, lost: 0, gd: 14, pts: 18 },
    { pos: 2, team: 'بايرن ميونخ', played: 6, won: 4, drawn: 1, lost: 1, gd: 9, pts: 13 },
    { pos: 3, team: 'مانشستر سيتي', played: 6, won: 4, drawn: 0, lost: 2, gd: 7, pts: 12 },
    { pos: 4, team: 'باريس سان جيرمان', played: 6, won: 3, drawn: 1, lost: 2, gd: 4, pts: 10 },
  ],
};

export const scorers: Record<string, Scorer[]> = {
  'الدوري الإنجليزي': [
    { rank: 1, name: 'إيرلينغ هالاند', team: 'مانشستر سيتي', goals: 19 },
    { rank: 2, name: 'محمد صلاح', team: 'ليفربول', goals: 16 },
    { rank: 3, name: 'أولي واتكينز', team: 'أستون فيلا', goals: 13 },
    { rank: 4, name: 'سون هيونغ مين', team: 'توتنهام', goals: 12 },
    { rank: 5, name: 'بوكايو ساكا', team: 'أرسنال', goals: 11 },
  ],
  'الدوري الإسباني': [
    { rank: 1, name: 'جود بيلينغهام', team: 'ريال مدريد', goals: 15 },
    { rank: 2, name: 'روبرت ليفاندوفسكي', team: 'برشلونة', goals: 14 },
    { rank: 3, name: 'أنطوان غريزمان', team: 'أتلتيكو مدريد', goals: 12 },
    { rank: 4, name: 'فينيسيوس جونيور', team: 'ريال مدريد', goals: 11 },
    { rank: 5, name: 'لياندرو بارديز', team: 'أتلتيك بلباو', goals: 9 },
  ],
  'دوري أبطال أوروبا': [
    { rank: 1, name: 'كيليان مبابي', team: 'ريال مدريد', goals: 8 },
    { rank: 2, name: 'هاري كين', team: 'بايرن ميونخ', goals: 7 },
    { rank: 3, name: 'إيرلينغ هالاند', team: 'مانشستر سيتي', goals: 6 },
    { rank: 4, name: 'عثمان ديمبيلي', team: 'باريس سان جيرمان', goals: 5 },
  ],
};

export const challenges: Challenge[] = [
  { title: 'حلبة التوقعات', text: 'أنشئ تحدياً خاصاً مع أصدقائك', icon: 'Users', color: 'green', page: 'challengeArena' },
  { title: 'جاوب واكسب', text: 'اختبر معلوماتك واربح بمبات', icon: 'CircleHelp', color: 'blue', page: 'challengeQuiz' },
  { title: 'تحدي الأبطال', text: 'توقع أبطال البطولات', icon: 'Crown', color: 'orange', page: 'challengeChampions' },
  { title: 'أنت المدرب', text: 'كوّن فريق أحلامك', icon: 'ShieldCheck', color: 'red', page: 'challengeCoach' },
  { title: 'متجر بمبا', text: 'استبدل بمباتك بالمكافآت', icon: 'ShoppingBag', color: 'teal', page: 'challengeStore' },
];

export const players: Player[] = [
  // ===== الدوري الإنجليزي =====
  { id: 1, name: 'إيرلينغ هالاند', team: 'مانشستر سيتي', position: 'مهاجم', price: 1800, marketValue: '180 مليون' },
  { id: 2, name: 'كيفن دي بروين', team: 'مانشستر سيتي', position: 'وسط', price: 950, marketValue: '95 مليون' },
  { id: 3, name: 'فيل فودين', team: 'مانشستر سيتي', position: 'وسط', price: 1300, marketValue: '130 مليون' },
  { id: 4, name: 'عمر مرموش', team: 'مانشستر سيتي', position: 'مهاجم', price: 850, marketValue: '85 مليون' },
  { id: 5, name: 'إيدرسون', team: 'مانشستر سيتي', position: 'حارس', price: 400, marketValue: '40 مليون' },
  { id: 6, name: 'روبن دياز', team: 'مانشستر سيتي', position: 'مدافع', price: 800, marketValue: '80 مليون' },
  { id: 7, name: 'محمد صلاح', team: 'ليفربول', position: 'جناح', price: 1450, marketValue: '145 مليون' },
  { id: 8, name: 'فيرجيل فان دايك', team: 'ليفربول', position: 'مدافع', price: 850, marketValue: '85 مليون' },
  { id: 9, name: 'أليسون بيكر', team: 'ليفربول', position: 'حارس', price: 650, marketValue: '65 مليون' },
  { id: 10, name: 'ترينت ألكسندر-أرنولد', team: 'ليفربول', position: 'مدافع', price: 1200, marketValue: '120 مليون' },
  { id: 11, name: 'بوكايو ساكا', team: 'أرسنال', position: 'جناح', price: 1450, marketValue: '145 مليون' },
  { id: 12, name: 'مارتن أوديغارد', team: 'أرسنال', position: 'وسط', price: 1100, marketValue: '110 مليون' },
  { id: 13, name: 'ديكلان رايس', team: 'أرسنال', position: 'وسط', price: 1150, marketValue: '115 مليون' },
  { id: 14, name: 'كول بالمر', team: 'تشيلسي', position: 'وسط', price: 1300, marketValue: '130 مليون' },
  { id: 15, name: 'إنزو فرنانديز', team: 'تشيلسي', position: 'وسط', price: 900, marketValue: '90 مليون' },
  { id: 16, name: 'سون هيونغ مين', team: 'توتنهام', position: 'جناح', price: 750, marketValue: '75 مليون' },
  { id: 17, name: 'جيمس ماديسون', team: 'توتنهام', position: 'وسط', price: 600, marketValue: '60 مليون' },
  { id: 18, name: 'برونو فيرنانديز', team: 'مانشستر يونايتد', position: 'وسط', price: 1000, marketValue: '100 مليون' },
  { id: 19, name: 'أليخاندرو غارناتشو', team: 'مانشستر يونايتد', position: 'جناح', price: 1050, marketValue: '105 مليون' },
  { id: 20, name: 'أمادو أونانا', team: 'مانشستر يونايتد', position: 'حارس', price: 350, marketValue: '35 مليون' },
  { id: 21, name: 'ألكسندر إيزاك', team: 'نيوكاسل', position: 'مهاجم', price: 1150, marketValue: '115 مليون' },
  { id: 22, name: 'برونو غيمارايش', team: 'نيوكاسل', position: 'وسط', price: 800, marketValue: '80 مليون' },
  { id: 23, name: 'أولي واتكينز', team: 'أستون فيلا', position: 'مهاجم', price: 950, marketValue: '95 مليون' },
  { id: 24, name: 'إيمليانو مارتينيز', team: 'أستون فيلا', position: 'حارس', price: 700, marketValue: '70 مليون' },
  { id: 25, name: 'جون ماكغين', team: 'أستون فيلا', position: 'وسط', price: 500, marketValue: '50 مليون' },
  // ===== الدوري الإسباني =====
  { id: 26, name: 'كيليان مبابي', team: 'ريال مدريد', position: 'مهاجم', price: 1700, marketValue: '170 مليون' },
  { id: 27, name: 'فينيسيوس جونيور', team: 'ريال مدريد', position: 'جناح', price: 1600, marketValue: '160 مليون' },
  { id: 28, name: 'جود بيلينغهام', team: 'ريال مدريد', position: 'وسط', price: 1700, marketValue: '170 مليون' },
  { id: 29, name: 'فيديريكو فالفيردي', team: 'ريال مدريد', position: 'وسط', price: 1000, marketValue: '100 مليون' },
  { id: 30, name: 'تيبو كورتوا', team: 'ريال مدريد', position: 'حارس', price: 800, marketValue: '80 مليون' },
  { id: 31, name: 'إيدير ميليتاو', team: 'ريال مدريد', position: 'مدافع', price: 850, marketValue: '85 مليون' },
  { id: 32, name: 'لامين يامال', team: 'برشلونة', position: 'جناح', price: 1650, marketValue: '165 مليون' },
  { id: 33, name: 'روبرت ليفاندوفسكي', team: 'برشلونة', position: 'مهاجم', price: 850, marketValue: '85 مليون' },
  { id: 34, name: 'بيدري', team: 'برشلونة', position: 'وسط', price: 1100, marketValue: '110 مليون' },
  { id: 35, name: 'رافينها', team: 'برشلونة', position: 'جناح', price: 1350, marketValue: '135 مليون' },
  { id: 36, name: 'غافي', team: 'برشلونة', position: 'وسط', price: 1200, marketValue: '120 مليون' },
  { id: 37, name: 'أنطوان غريزمان', team: 'أتلتيكو مدريد', position: 'مهاجم', price: 750, marketValue: '75 مليون' },
  { id: 38, name: 'خوليان ألفاريز', team: 'أتلتيكو مدريد', position: 'مهاجم', price: 1100, marketValue: '110 مليون' },
  { id: 39, name: 'نيكو ويليامز', team: 'أثلتيك بلباو', position: 'جناح', price: 900, marketValue: '90 مليون' },
  { id: 40, name: 'مارتن زوبيميندي', team: 'ريال سوسيداد', position: 'وسط', price: 800, marketValue: '80 مليون' },
  { id: 41, name: 'إيسكو', team: 'ريال بيتيس', position: 'وسط', price: 500, marketValue: '50 مليون' },
  { id: 42, name: 'أليكس باينا', team: 'فياريال', position: 'وسط', price: 700, marketValue: '70 مليون' },
  // ===== الدوري الإيطالي =====
  { id: 43, name: 'لاوتارو مارتينيز', team: 'إنتر ميلان', position: 'مهاجم', price: 850, marketValue: '85 مليون' },
  { id: 44, name: 'هاكان تشالهان أوغلو', team: 'إنتر ميلان', position: 'وسط', price: 620, marketValue: '62 مليون' },
  { id: 45, name: 'نيكولو باريلا', team: 'إنتر ميلان', position: 'وسط', price: 750, marketValue: '75 مليون' },
  { id: 46, name: 'ماركوس تورام', team: 'إنتر ميلان', position: 'مهاجم', price: 700, marketValue: '70 مليون' },
  { id: 47, name: 'رافائيل لياو', team: 'ميلان', position: 'جناح', price: 900, marketValue: '90 مليون' },
  { id: 48, name: 'تيو هيرنانديز', team: 'ميلان', position: 'مدافع', price: 700, marketValue: '70 مليون' },
  { id: 49, name: 'كريستيان بوليسيتش', team: 'ميلان', position: 'جناح', price: 750, marketValue: '75 مليون' },
  { id: 50, name: 'دوشان فلاهوفيتش', team: 'يوفنتوس', position: 'مهاجم', price: 650, marketValue: '65 مليون' },
  { id: 51, name: 'كينان يلدز', team: 'يوفنتوس', position: 'جناح', price: 850, marketValue: '85 مليون' },
  { id: 52, name: 'فيكتور أوسيمين', team: 'نابولي', position: 'مهاجم', price: 750, marketValue: '75 مليون' },
  { id: 53, name: 'ستانيسلاف لوبوتكا', team: 'نابولي', position: 'وسط', price: 550, marketValue: '55 مليون' },
  { id: 54, name: 'باولو ديبالا', team: 'روما', position: 'مهاجم', price: 500, marketValue: '50 مليون' },
  { id: 55, name: 'أرتيم دوفبيك', team: 'روما', position: 'مهاجم', price: 650, marketValue: '65 مليون' },
  { id: 56, name: 'أديمولا لوكمان', team: 'أتالانتا', position: 'مهاجم', price: 850, marketValue: '85 مليون' },
  { id: 57, name: 'تشارلز دي كيتيلاري', team: 'أتالانتا', position: 'مهاجم', price: 650, marketValue: '65 مليون' },
  { id: 58, name: 'مويس كين', team: 'فيورنتينا', position: 'مهاجم', price: 550, marketValue: '55 مليون' },
  // ===== الدوري الألماني =====
  { id: 59, name: 'هاري كين', team: 'بايرن ميونخ', position: 'مهاجم', price: 1150, marketValue: '115 مليون' },
  { id: 60, name: 'جمال موسيالا', team: 'بايرن ميونخ', position: 'وسط', price: 1400, marketValue: '140 مليون' },
  { id: 61, name: 'مايكل أوليس', team: 'بايرن ميونخ', position: 'جناح', price: 1000, marketValue: '100 مليون' },
  { id: 62, name: 'جوشوا كيميش', team: 'بايرن ميونخ', position: 'وسط', price: 850, marketValue: '85 مليون' },
  { id: 63, name: 'فلوريان فيرتز', team: 'باير ليفركوزن', position: 'وسط', price: 1500, marketValue: '150 مليون' },
  { id: 64, name: 'غرانيت تشاكا', team: 'باير ليفركوزن', position: 'وسط', price: 400, marketValue: '40 مليون' },
  { id: 65, name: 'فيكتور بونيفاس', team: 'باير ليفركوزن', position: 'مهاجم', price: 500, marketValue: '50 مليون' },
  { id: 66, name: 'سيرهو غيراسي', team: 'دورتموند', position: 'مهاجم', price: 850, marketValue: '85 مليون' },
  { id: 67, name: 'جوليان براندت', team: 'دورتموند', position: 'وسط', price: 450, marketValue: '45 مليون' },
  { id: 68, name: 'لوي أوبيندا', team: 'لايبزيغ', position: 'مهاجم', price: 750, marketValue: '75 مليون' },
  { id: 69, name: 'تشافي سيمونز', team: 'لايبزيغ', position: 'وسط', price: 1000, marketValue: '100 مليون' },
  { id: 70, name: 'دينيز أونداف', team: 'شتوتغارت', position: 'مهاجم', price: 600, marketValue: '60 مليون' },
  { id: 71, name: 'أنجيلو شتيلر', team: 'شتوتغارت', position: 'وسط', price: 650, marketValue: '65 مليون' },
  { id: 72, name: 'هوغو إيكيتيكي', team: 'آينتراخت فرانكفورت', position: 'مهاجم', price: 550, marketValue: '55 مليون' },
  // ===== الدوري الفرنسي =====
  { id: 73, name: 'عثمان ديمبيلي', team: 'باريس سان جيرمان', position: 'جناح', price: 950, marketValue: '95 مليون' },
  { id: 74, name: 'أشرف حكيمي', team: 'باريس سان جيرمان', position: 'مدافع', price: 1100, marketValue: '110 مليون' },
  { id: 75, name: 'فيتينيا', team: 'باريس سان جيرمان', position: 'وسط', price: 750, marketValue: '75 مليون' },
  { id: 76, name: 'برادلي باركولا', team: 'باريس سان جيرمان', position: 'جناح', price: 850, marketValue: '85 مليون' },
  { id: 77, name: 'وارين زائير-إيمري', team: 'باريس سان جيرمان', position: 'وسط', price: 800, marketValue: '80 مليون' },
  { id: 78, name: 'جيانلويجي دوناروما', team: 'باريس سان جيرمان', position: 'حارس', price: 600, marketValue: '60 مليون' },
  { id: 79, name: 'خفيشا كفاراتسخيليا', team: 'باريس سان جيرمان', position: 'جناح', price: 850, marketValue: '85 مليون' },
  { id: 80, name: 'ألكسندر لاكازيت', team: 'ليون', position: 'مهاجم', price: 400, marketValue: '40 مليون' },
  { id: 81, name: 'رايان شرقي', team: 'ليون', position: 'جناح', price: 550, marketValue: '55 مليون' },
  { id: 82, name: 'جوناثان ديفيد', team: 'ليل', position: 'مهاجم', price: 500, marketValue: '50 مليون' },
  { id: 83, name: 'ماسون غرينوود', team: 'مارسيليا', position: 'جناح', price: 650, marketValue: '65 مليون' },
  { id: 84, name: 'إيلي واي', team: 'مارسيليا', position: 'مهاجم', price: 700, marketValue: '70 مليون' },
  { id: 85, name: 'دينيس زكريا', team: 'موناكو', position: 'وسط', price: 450, marketValue: '45 مليون' },
  // ===== دوري روشن السعودي =====
  { id: 86, name: 'كريستيانو رونالدو', team: 'النصر', position: 'مهاجم', price: 1500, marketValue: '150 مليون' },
  { id: 87, name: 'ساديو ماني', team: 'النصر', position: 'جناح', price: 550, marketValue: '55 مليون' },
  { id: 88, name: 'سالم الدوسري', team: 'الهلال', position: 'جناح', price: 500, marketValue: '50 مليون' },
  { id: 89, name: 'نيمار', team: 'الهلال', position: 'جناح', price: 800, marketValue: '80 مليون' },
  { id: 90, name: 'سيرغي ميلينكوفيتش-سافيتش', team: 'الهلال', position: 'وسط', price: 600, marketValue: '60 مليون' },
  { id: 91, name: 'ألكسندر ميتروفيتش', team: 'الهلال', position: 'مهاجم', price: 750, marketValue: '75 مليون' },
  { id: 92, name: 'كاليدو كوليبالي', team: 'الهلال', position: 'مدافع', price: 450, marketValue: '45 مليون' },
  { id: 93, name: 'كريم بنزيما', team: 'الاتحاد', position: 'مهاجم', price: 900, marketValue: '90 مليون' },
  { id: 94, name: 'نغولو كانتي', team: 'الاتحاد', position: 'وسط', price: 450, marketValue: '45 مليون' },
  { id: 95, name: 'فابينيو', team: 'الاتحاد', position: 'وسط', price: 350, marketValue: '35 مليون' },
  { id: 96, name: 'رياض محرز', team: 'الأهلي', position: 'جناح', price: 550, marketValue: '55 مليون' },
  { id: 97, name: 'فرانك كيسي', team: 'الأهلي', position: 'وسط', price: 500, marketValue: '50 مليون' },
  { id: 98, name: 'إيفان توني', team: 'الأهلي', position: 'مهاجم', price: 600, marketValue: '60 مليون' },
];

export const storeItems = [
  { id: 1, name: 'كرة بمبا الرسمية', category: 'أدوات رياضية', cost: 5000, discount: '20%', store: 'محل الرياضة' },
  { id: 2, name: 'تيشرت توقعات بمبا', category: 'ملابس رياضية', cost: 3000, discount: '50%', store: 'محل الرياضة' },
  { id: 3, name: 'وجبة في مطعم', category: 'مطاعم', cost: 2000, discount: '70%', store: 'مطعم الشيف' },
  { id: 4, name: 'حذاء كرة قدم', category: 'أدوات رياضية', cost: 8000, discount: '30%', store: 'محل الرياضة' },
  { id: 5, name: 'كوبون خصم 20%', category: 'كوبونات', cost: 1000, discount: '20%', store: 'متجر عام' },
  { id: 6, name: 'كوبون خصم 50%', category: 'كوبونات', cost: 2500, discount: '50%', store: 'متجر عام' },
];

export const quizQuestions = [
  { id: 1, q: 'كم مرة فازت البرازيل بكأس العالم؟', options: ['3', '4', '5', '6'], answer: 2 },
  { id: 2, q: 'من صاحب أكبر عدد من أهداف دوري الأبطال؟', options: ['ميسي', 'رونالدو', 'بنزيما', 'ليفاندوفسكي'], answer: 1 },
  { id: 3, q: 'في أي سنة تأسس ريال مدريد؟', options: ['1899', '1902', '1905', '1910'], answer: 1 },
  { id: 4, q: 'من أفضل لاعب في العالم 2023؟', options: ['مبابي', 'ميسي', 'هالاند', 'بيلينغهام'], answer: 2 },
  { id: 5, q: 'كم فريق يشارك في كأس العالم؟', options: ['24', '32', '36', '48'], answer: 3 },
];

