/*
# نظام المكافآت — الأسئلة الرياضية + المشاركة + كود الدعوة

- `quiz_questions`: بنك أسئلة رياضية متنوع (يُعرض لكل مشترك بترتيب مختلف).
- `answer_quiz_question()`: يتحقق الخادم من الإجابة ويُكافئ مرة واحدة لكل سؤال (مفتاح idempotency).
- `claim_reward()`: مكافأة عامة (مشاركة يومية / تحديات) بمفتاح يمنع التكرار.
- `apply_invite()`: من يسجّل بكود دعوة → الداعي يحصل على 50 بمبة تلقائياً (مرة واحدة لكل مدعو).
- `referral_code`: كود دعوة فريد لكل عضو (BMBA-XXXXXX).
*/

-- ============ 1) بنك الأسئلة الرياضية ============
create table if not exists public.quiz_questions (
  id bigint generated by default as identity primary key,
  category text not null default 'رياضة عامة',
  question text not null unique,
  options text[] not null,
  answer_index int not null check (answer_index between 0 and 3),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.quiz_questions (category, question, options, answer_index) values
('كأس العالم', 'من فاز بلقب كأس العالم 2022 في قطر؟', array['فرنسا','الأرجنتين','البرازيل','البرتغال'], 1),
('كأس العالم', 'من هو هداف كأس العالم 2022؟', array['جوليان ألفاريز','كرستيانو رونالدو','كيليان مبابي','هاراريث'], 2),
('كأس العالم', 'كم عدد مرات فوز البرازيل بكأس العالم؟', array['4','5','3','6'], 1),
('كأس العالم', 'في أي عام أُقيمت أول نسخة من كأس العالم؟', array['1926','1934','1930','1938'], 2),
('كأس العالم', 'من هو الهداف التاريخي لكأس العالم؟', array['رونالدو','ميروسلاف كلوزه','ميسي','بيليه'], 1),
('كأس العالم', 'أي دولة استضافت كأس العالم 2018؟', array['قطر','ألمانيا','البرازيل','روسيا'], 3),
('كأس العالم', 'كم عدد الفرق المشاركة في كأس العالم 2022؟', array['32','24','48','36'], 0),
('أوروبا', 'أي منتخب فاز بكأس الأمم الأوروبية يورو 2024؟', array['إيطاليا','إنجلترا','إسبانيا','فرنسا'], 2),
('أوروبا', 'كم مرة فاز ريال مدريد بدوري أبطال أوروبا حتى 2024؟', array['14','13','15','12'], 2),
('أوروبا', 'من هو الهداف التاريخي لدوري أبطال أوروبا؟', array['ميسي','كرستيانو رونالدو','بنزيما','ليفاندوفسكي'], 1),
('أوروبا', 'أي نادٍ فاز بالدوري الإنجليزي الممتاز موسم 2023-24؟', array['أرسنال','ليفربول','مانشستر سيتي','تشيلسي'], 2),
('أوروبا', 'أي نادٍ فاز بالدوري الإسباني موسم 2023-24؟', array['برشلونة','ريال مدريد','أتلتيكو مدريد','ريال سوسيداد'], 1),
('أوروبا', 'أي نادٍ يُلقب بـ"البلوغرانا"؟', array['ريال مدريد','إشبيلية','برشلونة','فالنسيا'], 2),
('أوروبا', 'أي نادٍ يُلقب بـ"البيانكونيري"؟', array['ميلان','يوفنتوس','إنتر','روما'], 1),
('أوروبا', 'أي نادٍ ألماني فاجأ أوروبا وفاز بالدوري الألماني 2023-24؟', array['بايرن ميونخ','دورتموند','ليفركوزن','لايبزيغ'], 2),
('أوروبا', 'من هو مدرب مانشستر سيتي؟', array['كلوب','غوارديولا','أنشيلوتي','مورينيو'], 1),
('أوروبا', 'من هو مدرب ريال مدريد (2024)؟', array['زيدان','أنشيلوتي','راؤول','بيب'], 1),
('أوروبا', 'كم عدد فرق الدوري الإنجليزي الممتاز؟', array['18','22','20','24'], 2),
('أوروبا', 'أي فريق فاز بكأس الاتحاد الإنجليزي 2024؟', array['مانشستر سيتي','مانشستر يونايتد','ليفربول','أرسنال'], 1),
('أوروبا', 'من هو الهداف التاريخي للدوري الإنجليزي الممتاز؟', array['واين روني','هاري كين','آلان شيرر','مبابي'], 2),
('أوروبا', 'أي مدينة استضافت نهائي دوري أبطال أوروبا 2024؟', array['باريس','مدريد','لندن','إسطنبول'], 2),
('نجوم', 'من فاز بالكرة الذهبية 2024؟', array['فينيسيوس','رودري','بلينغهام','مبابي'], 1),
('نجوم', 'كم مرة فاز ميسي بالكرة الذهبية حتى 2023؟', array['7','9','8','6'], 2),
('نجوم', 'من هو الهداف التاريخي لمنتخب البرتغال؟', array['نونو غوميش','فيليكس','كرستيانو رونالدو','برناردو سيلفا'], 2),
('نجوم', 'من هو أول لاعب في التاريخ يتجاوز 900 هدف رسمي؟', array['بيليه','ميسي','كرستيانو رونالدو','ليفاندوفسكي'], 2),
('نجوم', 'من قاد الأرجنتين وقبّل الكأس بعد نهائي قطر 2022؟', array['ميسي','دي ماريا','ألفاريز','مونتيل'], 0),
('نجوم', 'من هو الحارس الفائز بالقفاز الذهبي في مونديال 2022؟', array['كورتو','إيمي مارتينيز','اللسون','دوناروما'], 1),
('نجوم', 'من هو أفضل لاعب في العالم (جائزة ذا بيست) لعام 2023؟', array['هالاند','مبابي','ميسي','فينيسيوس'], 2),
('قوانين', 'كم دقيقة تستغرق المباراة الرسمية كاملة بدون وقت إضافي؟', array['80','90','100','120'], 1),
('قوانين', 'كم عدد البطاقات الصفراء التي تُخرج اللاعب من المباراة الواحدة؟', array['1','3','2','4'], 2),
('قوانين', 'كم عدد لاعبي كل فريق داخل الملعب في بداية المباراة؟', array['10','12','11','13'], 2),
('عربية', 'أي منتخب فاز بكأس العرب 2021؟', array['المغرب','الجزائر','مصر','السعودية'], 1),
('عربية', 'أي نادٍ فاز بدوري روشن السعودي 2023-24؟', array['النصر','الاتحاد','الهلال','الأهلي'], 2),
('عربية', 'أي نادٍ سعودي يُلقب بـ"العميد"؟', array['الهلال','النصر','الأهلي','الاتحاد'], 3),
('عربية', 'من هو مدرب الهلال السعودي الفائز بالثلاثية (2024)؟', array['رامون دياز','جورجي جيسوس','فيرغوسون','باولو سوزا'], 1),
('عربية', 'أي منتخب فاز بكأس أمم آسيا 2023 المقامة في قطر؟', array['إيران','كوريا','قطر','العراق'], 2),
('عربية', 'أي منتخب عربي بلغ نصف نهائي كأس العالم 2022؟', array['المغرب','السعودية','الجزائر','مصر'], 0),
('عربية', 'أي منتخب عربي فاز بكأس آسيا مرتين متتاليتين (2019 و2023)؟', array['اليابان','قطر','السعودية','أستراليا'], 1),
('أمريكا الجنوبية', 'أي منتخب فاز بكوبا أمريكا 2024؟', array['الأرجنتين','البرازيل','كولومبيا','أوروغواي'], 0),
('أمريكا الجنوبية', 'كم مرة فازت الأرجنتين بكأس العالم حتى 2022؟', array['2','4','5','3'], 3),
('إفريقيا', 'أي منتخب فاز بكأس أمم إفريقيا 2023 (يناير 2024)؟', array['ساحل العاج','السنغال','مصر','نيجيريا'], 0),
('إفريقيا', 'كم مرة فازت مصر بأمم إفريقيا (رقم قياسي)؟', array['5','6','8','7'], 3)
on conflict (question) do nothing;

-- ============ 2) كود الدعوة في الملف الشخصي ============
alter table public.profiles add column if not exists referral_code text;
alter table public.profiles add column if not exists invited_by uuid references public.profiles(id) on delete set null;
create unique index if not exists idx_profiles_referral_code on public.profiles (referral_code) where referral_code is not null;

-- ============ 3) محفظة المكافآت — تطبيق رصيد بدون بوابة الإدارة (يُستدعى من دوال المكافآت فقط) ============
create or replace function public.reward_apply_balance(
  p_user_id uuid,
  p_amount int,
  p_source_type text,
  p_source_id text,
  p_idempotency_key text
) returns public.wallet_transactions
language plpgsql security definer set search_path = public as $$
declare
  v_balance integer;
  v_existing public.wallet_transactions;
begin
  if p_idempotency_key is not null then
    select * into v_existing from public.wallet_transactions where idempotency_key = p_idempotency_key;
    if v_existing.id is not null then return v_existing; end if;
  end if;

  select bamba_balance into v_balance from public.profiles where id = p_user_id for update;
  if v_balance is null then raise exception 'USER_NOT_FOUND'; end if;

  update public.profiles set bamba_balance = bamba_balance + p_amount where id = p_user_id
  returning bamba_balance into v_balance;

  insert into public.wallet_transactions (user_id, type, amount, balance_before, balance_after, source_type, source_id, created_by, idempotency_key, metadata)
  values (p_user_id, 'reward', p_amount, v_balance - p_amount, v_balance, p_source_type, p_source_id, p_user_id, p_idempotency_key, '{}'::jsonb)
  returning * into v_existing;

  return v_existing;
end $$;

revoke all on function public.reward_apply_balance(uuid, int, text, text, text) from public;

-- ============ 4) جلب أسئلة بترتيب مختلف لكل مشترك ============
create or replace function public.get_quiz_questions(p_count int default 5)
returns table(id bigint, category text, question text, options text[])
language sql security definer set search_path = public as $$
  select q.id, q.category, q.question, q.options
  from public.quiz_questions q
  where q.active
  order by md5(q.id::text || '|' || coalesce(auth.uid()::text, 'anon'))
  limit p_count;
$$;

revoke all on function public.get_quiz_questions(int) from public;
grant execute on function public.get_quiz_questions(int) to authenticated;

-- ============ 5) الإجابة على سؤال — تحقق الخادم + مكافأة مرة واحدة ============
create or replace function public.answer_quiz_question(p_question_id bigint, p_answer_index int, p_reward int default 5)
returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  v_q public.quiz_questions%rowtype;
  v_correct boolean;
  v_tx public.wallet_transactions;
  v_key text;
begin
  select * into v_q from public.quiz_questions where id = p_question_id and active;
  if v_q.id is null then return jsonb_build_object('error', 'QUESTION_NOT_FOUND'); end if;

  v_correct := (p_answer_index = v_q.answer_index);
  if v_correct and p_reward > 0 then
    v_key := 'quiz_' || auth.uid()::text || '_' || p_question_id::text;
    select * into v_tx from public.wallet_transactions where idempotency_key = v_key;
    if v_tx.id is null then
      v_tx := public.reward_apply_balance(auth.uid(), p_reward, 'quiz', p_question_id::text, v_key);
      return jsonb_build_object('correct', true, 'earned', p_reward, 'balance', v_tx.balance_after);
    end if;
    return jsonb_build_object('correct', true, 'earned', 0, 'balance', v_tx.balance_after, 'already', true);
  end if;

  return jsonb_build_object('correct', v_correct, 'earned', 0);
end $$;

revoke all on function public.answer_quiz_question(bigint, int, int) from public;
grant execute on function public.answer_quiz_question(bigint, int, int) to authenticated;

-- ============ 6) مكافأة عامة بمفتاح يمنع التكرار (مشاركة يومية / تحديات) ============
create or replace function public.claim_reward(p_source_type text, p_source_id text, p_amount int, p_idempotency_key text)
returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  v_tx public.wallet_transactions;
  v_key text;
begin
  v_key := p_idempotency_key;
  select * into v_tx from public.wallet_transactions where idempotency_key = v_key;
  if v_tx.id is null then
    v_tx := public.reward_apply_balance(auth.uid(), p_amount, p_source_type, p_source_id, v_key);
    return jsonb_build_object('ok', true, 'amount', v_tx.amount, 'balance', v_tx.balance_after);
  end if;
  return jsonb_build_object('ok', false, 'already', true, 'amount', 0, 'balance', v_tx.balance_after);
end $$;

revoke all on function public.claim_reward(text, text, int, text) from public;
grant execute on function public.claim_reward(text, text, int, text) to authenticated;

-- ============ 7) تطبيق كود الدعوة عند التسجيل → مكافأة الداعي ============
create or replace function public.apply_invite(p_referral_code text)
returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  v_inviter public.profiles%rowtype;
  v_tx public.wallet_transactions;
  v_new uuid := auth.uid();
  v_key text;
begin
  select * into v_inviter
  from public.profiles
  where upper(referral_code) = upper(trim(p_referral_code)) and referral_code is not null;

  if v_inviter.id is null then return jsonb_build_object('error', 'INVALID_CODE'); end if;
  if v_inviter.id = v_new then return jsonb_build_object('error', 'SELF_INVITE'); end if;

  update public.profiles set invited_by = v_inviter.id where id = v_new and invited_by is null;

  v_key := 'invite_' || v_inviter.id::text || '_' || v_new::text;
  select * into v_tx from public.wallet_transactions where idempotency_key = v_key;
  if v_tx.id is null then
    v_tx := public.reward_apply_balance(v_inviter.id, 50, 'invite', v_new::text, v_key);
  end if;

  return jsonb_build_object('ok', true, 'inviter', v_inviter.username, 'reward', 50);
end $$;

revoke all on function public.apply_invite(text) from public;
grant execute on function public.apply_invite(text) to authenticated;